name: SonarQube Practise
on:
  push:
    branches:
    - master
jobs:
  sonarqube-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@v2
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_SECRET}}
        SONAR_HOST_URL: https://sonarcloud.io

    - name: Quality Gate Check
      id: quality_gate
      uses: sonarsource/sonarqube-quality-gate-action@master 
      timeout-minutes: 5
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_SECRET}}